### ISSUE TITLE
Shodan Analyzer

### ISSUE THREAD

**Issue by fbb6f493cb2c90cde960** [CERT-BDF/Cortex-Analyzers#106]
# Shodan Analyzer

### Request Type
Bug / Analyzer / Feature

### Work Environment
N/A

### Description
Shodan provides a REST API to search hosts
Documentation is available at https://developer.shodan.io/api
To use the API you need to have an API key, which you can get for free by creating a Shodan account.

**Comment by saadkadhi** [comment]
@sebdraven is working on this one.
