### ISSUE TITLE
CIRCL.lu PassiveDNS Analyzer

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/Cortex-Analyzers#11]
### Request Type
Analyzer Request

### Work Environment
NA

### Analyzer Description
Create an analyzer to tap into [CIRCL.lu PassiveDNS](https://www.circl.lu/services/passive-dns/) service.

**Comment by saadkadhi** [comment]
@3c7 has proposed to create it.

**Comment by saadkadhi** [comment]
@3c7 any update on this one and the other few analyzers you would be contributing? Do you need any help from us?

**Comment by 3c7** [comment]
Hey @saadkadhi, currently working on google safebrowsing analyzer. Hope I'm able to publish the analyzers next week.
![Analyzers](https://cloud.githubusercontent.com/assets/2846609/24196476/3906be52-0efe-11e7-85d4-fc986cfc07fc.png)
(Malwr.com uses ReCaptcha for the login and searching for hashes is not allowed through the API, so that analyzer is not ready to use at the moment)

Updated cortexutils to python 3, except for the `artifacts` part, because I don't know for what it is used.

**Comment by nadouani** [comment]
Hi @3c7,

just for information, the artifacts part will be used in the upcoming versions of TheHive to allow user to import observables coming from an analyzer report.

`cortexutils` comps with a default implementation which is using ioc-parser to extract observables from the report, but you can implement your own `artifacts()` method (it will override the default method provided by `cortexutils.Analyzer`super class.

That said, we will upgrade cortexutils to make sure it uses a fork of `ioc-parser` that is python3 compatible

Thanks

**Comment by nadouani** [comment]
@3c7 could you please share the updates you made to cortexutils? we can include the in the next release ;) 
If so, just create a pull request.

Thanks

**Comment by 3c7** [comment]
@nadouani Ah, thank you. My cortexutils-implementation is basically a clone of yours without the ioc-parser dependent artifacts function plus have the `raw` report as standard summary. ;)
I will review my code and create a pull request after that.

**Comment by saadkadhi** [comment]
Thanks a lot @3c7. We are looking forward to your contributions. If you also use TheHive and feel comfortable with AngularJS, we'd appreciate it if you submit short and long report templates for your analyzer set. Otherwise we'll take care of those.

**Comment by 3c7** [comment]
I've created templates for all of my analyzers, but maybe you can improve them. I'm not that familiar with Angular.
