### ISSUE TITLE
Cuckoo Analyzer requires final slash

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/Cortex-Analyzers#113]
### Request Type
Analyzer

### Work Environment
N/A

### Description
If Cuckoo runns on a different Port (e.g. 1234) the URL must be in the format:
http://cuckoo.tld:1234/
Note the slash at the end (!).
This is not what the user expects

### Steps to Reproduce
Configure Cuckoo API on a different port.

### Possible Solutions
Dynamically add the / in the Python script.

**Comment by saadkadhi** [comment]
@garanews can you please take charge of this enhancement request when you have time?

**Comment by saadkadhi** [comment]
@garanews when ready can you submit a PR please against develop? Thanks.

**Comment by garanews** [comment]
I PRed already against master couple of weeks ago :)

**Comment by nadouani** [comment]
I don't think there is a PR here @garanews, you fixed that on https://github.com/LDO-CERT/Cortex-Analyzers/commit/9d65fb9993e2a052ef328c9508a1844f0ff8e49f but didn't submit a PR to this repo

**Comment by garanews** [comment]
You right! Now should be there:
https://github.com/CERT-BDF/Cortex-Analyzers/pull/100
