### ISSUE TITLE
Virusshare short report enhancements if SHA1 hash passed

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/Cortex-Analyzers#115]
@garanews reported that the behavior of the virusshare analyzer is not correct, if a sha1 hash is passed to the analyzer. It should display the short report as info or smth like that, but not as malicious-tag.

I'll take a look at it, if I find some time in the next days.

**Comment by garanews** [comment]
It seems I had something wrong in the code that was generating this:
![image](https://user-images.githubusercontent.com/16938405/31822959-cd4f4c48-b5aa-11e7-90fb-847de95d1235.png)

With last version of your code is ok:
![image](https://user-images.githubusercontent.com/16938405/31823038-05d6253c-b5ab-11e7-9465-e75b442fd529.png)

Sorry for that,

**Comment by 3c7** [comment]
Oh, okay. Glad it works.
