### ISSUE TITLE
Censys.io analyzer

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/Cortex-Analyzers#135]
## About Censys
Censys is a search engine that enables researchers to ask questions about the hosts and networks that compose the Internet. Censys collects data on hosts and websites through daily ZMap and ZGrab scans of the IPv4 address space, in turn maintaining a database of how hosts and websites are configured. Researchers can interact with this data through a search interface, report builder, and SQL engine. Details on the Censys architecture are available in our research paper. [-> About Censys.io](https://censys.io/about)

---------------------------------------------

Think an analyzer for censys.io could be useful, I'll create one if I find some time in the next days.

**Comment by BrevilleBro** [comment]
Thanks @3c7 , let us know if you need any help with it, as this is something we are interested in as well :)

**Comment by 3c7** [comment]
It would be great to know which use cases are interesting for your work, so I know what to implement. I'm just getting to know censys.io, so mayne I'm not aware of certain possible use cases. :)

**Comment by 3c7** [comment]
Okay, let me see what info I can fetch over the API. I'll develop the analyzer this Friday, probably.

**Comment by BrevilleBro** [comment]
Thanks @3c7! Looking forward to it.

**Comment by 3c7** [comment]
Created a PR for a first version. Currently, it uses the `view` API-endpoint which returns the exact object (certificate or host based on ip or domain). If you have some ideas what to display in the reports additionally, I'd like to hear (read) them.

**Comment by nadouani** [comment]
The PR #153 has been merged into develop branch
