### ISSUE TITLE
Hippocampe Analyzer Fails

### ISSUE THREAD

**Issue by treed593** [CERT-BDF/Cortex-Analyzers#137]
### Request Type
Bug

### Work Environment
Production

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Mac osX
| Cortex Analyzer Name      | Hipposcore_2_0
| Cortex Analyzer Version   | 2.0
| Cortex Version            | 1.1.4
| Browser type & version    | Google Chrome 62.0.3202.89

### Description
When running a job against the Hippocampe Analyzer, I get the following returned

`{
  "errorMessage": "Hippocampe: HTTP Error 405: METHOD NOT ALLOWED",
  "input": {
    "dataType": "ip",
    "config": {
      "url": "https://hippocampe.ourdomain.com/hippocampe",
      "max_tlp": 3,
      "check_tlp": false,
      "service": "hipposcore"
    },
    "tlp": 2,
    "data": "{{ip_query_redacted}}"
  },
  "success": false
}`

### Steps to Reproduce
1. New Analysis
2. Data Type: ip
3. Data: ip_address
4. Select Hipposcore_2_0

### Complementary information
No corresponding job is showing up in Hippocampe

**Comment by ninSmith** [comment]
Hey,

May I have a look to your cortex configuration ?
Especially the part about Hippocampe

Thx

**Comment by treed593** [comment]
`    # Hippocampe: this analyzer  queries  TheHive  Project's  Hippocampe
    # product. You need to install it and provide the corresponding URL.
    Hippocampe {
      url="https://hippocampe.ourdomain.com/hippocampe"
    }
`

**Comment by ninSmith** [comment]
Could you try:

```
url="https://hippocampe.ourdomain.com"
```

And see if it works ?

**Comment by treed593** [comment]
Exactly what I needed! Thanks @ninSmith
