### ISSUE TITLE
MISP Analyzer

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/Cortex-Analyzers#14]
### Request Type
Analyzer Request

### Work Environment
NA

### Analyzer Description
Create an analyzer that can query one or several MISP instances.

The analyzer must be able to ingest observables, query [MISP](http://www.misp-project.org/) instances and provide the number of events where the observable can be found as a short report. The long analyzer report should contain useful metadata about the associated events if any and hyperlinks to access them.

### Additional Information
TheHive should be able to preview and import the events of interest once this analyzer is executed.

**Comment by saadkadhi** [comment]
@3c7 proposed to provide this analyzer.

**Comment by saadkadhi** [comment]
@3c7 If you are haven't started working on this analyzer, please drop it as @ant1 created one already and we are currently reviewing it. But if it's too late, that is just fine. We'll consider your pull request and compare both analyzers to add any useful features @ant1 might have missed. Sorry for any inconvenience.

**Comment by 3c7** [comment]
@saadkadhi It's already in use here. ;) I will upload all of my analyzers to our repo then we're able to choose what to include in this one. :)
