### ISSUE TITLE
 "VirusTotal_Scan" analyzer is not checking for TLP

### ISSUE THREAD

**Issue by jeromeleonard** [CERT-BDF/Cortex-Analyzers#2]
Setting TLP:AMBER or up is not avoiding sending files to VT for scan.
there is no `max_tlp` in the Virustotal scan analyser configuration, and `tlp` is not checked in the main program

**Comment by commiaI** [comment]
Hi !

Little error in the following file : https://github.com/CERT-BDF/Cortex-Analyzers/blob/master/analyzers/Fortiguard/Fortiguard_URLCategory.json
