### ISSUE TITLE
Cuckoo Sandbox Analyzer

### ISSUE THREAD

**Issue by benmeyer50** [CERT-BDF/Cortex-Analyzers#23]
### Request Type
Analyzer Request

### Work Environment
N/A

### Problem Description
Create an analyzer that will submit files to a local cuckoo sandbox instance and retrieve the report that is generated

**Comment by 3c7** [comment]
Is someone working on this? (@garanews ?)

**Comment by garanews** [comment]
Hello,
I am working on this, I modified code from JSB analyzer but not finished yet, like missing templates and clean code and choose useful output.
I will try to post code tomorrow.

**Comment by saadkadhi** [comment]
Thanks @garanews. We are looking forward to your contribution. Please do not hesitate to contact us on [Gitter](https://gitter.im/TheHive-Project/TheHive) should you need any help.

**Comment by 3c7** [comment]
Yesterday I set up a test cuckoo environment, so I could help, too.

**Comment by garanews** [comment]
I am at this point:
https://github.com/garanews/Cortex-Analyzers/tree/master/analyzers/CuckooSandbox
![cuckooanalyzer](https://cloud.githubusercontent.com/assets/16938405/25735480/f0e0c880-316b-11e7-8fdc-2a1dde56f08b.PNG)

**Comment by 3c7** [comment]
@garanews Looks good! If you need help just write over gitter.
