### ISSUE TITLE
Working on analyzers: CIRCL.lu PassiveSSL/DNS, CERT.AT PassiveDNS, MISP, IntelMQ, VMRay, Google Safebrowsing, URLQuery, yara

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/Cortex-Analyzers#3]
Hello guys,

great project so far! As @MichaelDwucet already mentioned, I'm working on some analyzers right now. This is just fyi, will provide details for each analyzer later on.

**Comment by saadkadhi** [comment]
Thanks @3c7. That would be great. I have created Issues #11 #12 #13 #14 #15 #16 #17 #18 #19 to track the implementations of each analyzer instead of keeping a single issue for all of them.

I am going to go ahead and close this one.
