### ISSUE TITLE
Fortiguard API Changed

### ISSUE THREAD

**Issue by bullerdude** [CERT-BDF/Cortex-Analyzers#37]
### Request Type
Bug

### Problem Description
Fortiguard have change their online free API meaning that the analyser is not working. It looks like the new version provide less info so the webscraping code will need to be updated as well. The new URL is: http://www.fortiguard.com/webfilter?q=www.google.com.

**Comment by saadkadhi** [comment]
Hi @bullerdude 

Thank you for reporting this issue. @ecapuano, would you have time to look into this please?

**Comment by ecapuano** [comment]
Sure thing. I had a feeling that would happen eventually, wish they'd offer a public API.

**Comment by saadkadhi** [comment]
HI @ecapuano 

Any update on this front?

Thanks in advance!

**Comment by ecapuano** [comment]
Working on it. Running tests to see if the scrape method is sustainable...Will post back very soon.

**Comment by ecapuano** [comment]
Fixed -> https://github.com/CERT-BDF/Cortex-Analyzers/pull/51

**Comment by jeromeleonard** [comment]
reviewed, validated.
