### ISSUE TITLE
Cut python 2 dependency by replacing ioc-parser in cortexutils.analyzer

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/Cortex-Analyzers#4]
### Request Type
Feature Request

### Content
Hello guys,

I just skimmed through analyzer.py to see, if it's possible to use the `Analyzer`-class with python 3. The problematic dependency in this case is `pdfminer` which is not in use, basically, because the parser is always called with `txt` and `json` parameters.

Would if be possible to replace it with an self-implemented function (more or less) easily?

Lots of modules I depend on use python 3 and I just thought it would be great to directly start with python 3 here.

Have a nice day
3c7

**Comment by nadouani** [comment]
Closing this issue, fix by [Automatic ioc extraction using RegEx](https://github.com/CERT-BDF/Cortex-Analyzers/pull/40)
