### ISSUE TITLE
GPF DNS Block List Analyzer

### ISSUE THREAD

**Issue by juanveloso** [CERT-BDF/Cortex-Analyzers#43]
### Request Type
Feature Request

I would like to know if worth to make an analyzer that gets IPs from GPF DNS Block List (https://www.gpf-comics.com/dnsbl/) to use with Cortex.

**Comment by saadkadhi** [comment]
Hi @juanveloso. If that's something you need within your environment, please go ahead and make an analyzer for that purpose. But this seems to rather an edge case. As a consequence, we may not include it in the analyzer packages we publish. That shouldn't prevent you from posting it somewhere and we'll point users who request it to your site.

**Comment by juanveloso** [comment]
Hello @saadkadhi.
Thank you for your feedback!
Hope to help in another way ;)

**Comment by geekscrapy** [comment]
Issue reference created by mistake...
