### ISSUE TITLE
TOR Exit Nodes IPs Analyzer

### ISSUE THREAD

**Issue by juanveloso** [CERT-BDF/Cortex-Analyzers#45]
### Request Type
Feature Request

I would like to know if worth to make an analyzer that identify IPs from a list of Tor Exit Nodes (https://check.torproject.org/exit-addresses and/or http://torstatus.blutmagie.de/ip_list_exit.php/Tor_ip_list_EXIT.csv) to use with Cortex.

**Comment by saadkadhi** [comment]
@sebdraven has kindly offered to develop this analyzer. TIA.

**Comment by nadouani** [comment]
Both PRs have been merged into `develop` branch, and will be released on 1.8.0 release
