### ISSUE TITLE
Analyzer Rate Limiting

### ISSUE THREAD

**Issue by JohnOmernik** [CERT-BDF/Cortex-Analyzers#5]
# Analyzer Rate Limiting
### Request Type
Feature Request

### Work Environment

NA

### Problem Description
It would be nice if we could have a way to rate limit outgoing requests in such a way that informs the user of high volumes, thus delayed response. Since we are hitting external systems, we don't want to be banned for abuse reasons. (Even when there are keys involved, some systems hold back, or charge per request

**Comment by saadkadhi** [comment]
I opened a [Cortex issue](https://github.com/CERT-BDF/Cortex/issues/6) to track this desirable feature. I am closing this one to avoid duplication.
