### ISSUE TITLE
[Bug] Custom responder not working after upgrade to cortex 3

### ISSUE THREAD

**Issue by anscz** [CERT-BDF/Cortex-Analyzers#542]
**Describe the bug**
After upgrade theHive, Cortex and elasticsearch to:
**Cortex:**
Cortex3.0.0-1
Elastic4Play1.11.5
Play2.6.23
Elastic4s6.5.1
ElasticSearch client6.5.2
**theHive**
TheHive3.4.0-1
Elastic4Play1.11.5
Play2.6.23
Elastic4s6.5.1
ElasticSearch6.5.2

I'm using custom responder to reply on reported phishing emails by phish button. This responder is based on official Mailer responder, modifications are just way how email is handled (adding custom body, taking email from tag, different body for different resolution, etc..).
After upgrade all the time I'm recieving error:
`"errorMessage": "Cannot run program \"/opt/cortex/Cortex-Analyzers/responders/phishingResponder/phishingResponder.py SPAM\" (in directory \"/opt/cortex/Cortex-Analyzers/responders\"): error=2, No such file or directory",`

path doublechecked, as well I run script localy from console on cortex server under cortex user permissions without any issue.

any suggestion would be more than wellcome.

**Comment by 3c7** [comment]
Have you followed https://github.com/TheHive-Project/CortexDocs/blob/master/migration_guide.md for the update and also updated your cortexutils?

**Comment by anscz** [comment]
I hope so, elastic configuration updated, Cortexutils updated, responder.path changed to responder.urls,  I'm using process based responder so there should be no need for any other change. 
May be just a question those *.json catalog files are mentioned just for docker based responders or as well for process based? 
Thanks

**Comment by ptobis** [comment]
Have you tried to follow this comment: https://github.com/TheHive-Project/Cortex/issues/182#issuecomment-489615808

**Comment by ptobis** [comment]
Maybe the problem is that Cortex is looking for a script file "phishingResponder.py SPAM" instead of "phishingResponder.py". Are you sure the "command" parameter in a JSON file contains the script name without any additional text?

**Comment by anscz** [comment]
it contains that "tag" because I have 4 different .json configuration to distinguish between response template I want to use. Script itself without parameter doesn't work there need to be one of VALID | PHISHING | SPAM | REMOVED . Each of them has defined in scrtipt different email body.
Is tehere any change in terms how command parameter is parsed in cortex 2.x and 3.x ? because for cortex 2.x that works fine. If you want you can check script and config here https://github.com/anscz/phishingResponder still some to do needs to be done, like move body template to cortex config to simplify changes in text, etc...

**Comment by 3c7** [comment]
That seems to be the issue at all. You can pass the needed keyword via config like
```
{
  "name": "reply as SPAM",
  "version": "1.0",
  "author": "Stepan Huzlik",
  "url": "https://github.com/anscz/phishingResponder",
  "license": "AGPL-V3",
  "description": "Send an email response",
  "dataTypeList": ["thehive:case"],
  "command": "phishingResponder/phishingResponder.py SPAM",
  "baseConfig": "phishingResponder",
  "config": {
    "mailType": "spam"
  },
  "configurationItems": [
    {
      "name": "from",
      "description": "email address from which the mail is send",
      "type": "string",
      "multi": false,
      "required": true
    },
    {
      "name": "smtp_host",
      "description": "SMTP server used to send mail",
      "type": "string",
      "multi": false,
      "required": true,
      "defaultValue": "localhost"
    },
    {
      "name": "smtp_port",
      "description": "SMTP server port",
      "type": "number",
      "multi": false,
      "required": true,
      "defaultValue": "25"
    }
  ]
}
```
and you should be able to check the parameter in your script like `self.get_param('config.mailType', None, 'Mail type not given!')`

**Comment by anscz** [comment]
I did all modifications you can review it in my repo, now it's possible to change body from Cortex GUI and pass Case title to the body text by $title.
It would be super nice to have posibility click on responder and after that on popup window select email type, but I didn't find way how to do that on current theHive.
Thanks once again & BR
