### ISSUE TITLE
Analyzer Caching

### ISSUE THREAD

**Issue by JohnOmernik** [CERT-BDF/Cortex-Analyzers#6]
# Analyzer Caching
### Request Type
Feature Request

### Work Environment

NA

### Problem Description
For analyzers, it would be nice to be able to identify a caching mechanism (say the Elastic Search cluster used for the hive) in such a way, that we could tune analyzers to check cache, and if there are hits within the specified timeline, that it returns the result from cache rather than requerying the endpoint in the analyzer. This would allow more efficient use of analyzer apis especially those that charge per request.

**Comment by saadkadhi** [comment]
@JohnOmernik We are tracking this feature request through [Persistence and Report Caching](https://github.com/CERT-BDF/Cortex/issues/5) and we have slated it for Cortex 2. I am closing this one.
