### ISSUE TITLE
Missing newlines in requirements.txt

### ISSUE THREAD

**Issue by Popsiclestick** [CERT-BDF/Cortex-Analyzers#60]
There were no newlines on the `GoogleSafebrowsing/requirements.txt` and `Virusshare/requirements.txt`

This caused values to concatenate and error out if you wanted to do `pip install $(cat /opt/Cortex-Analyzers/analyzers/*/requirements.txt | sort -u)` or some similar mass install of the required libraries. 

Pull request coming shortly.

**Comment by Lost4Now** [comment]
I used the following command and it worked for me.  This might a solution in the future just in case the new lines are missed again.

find '/opt/Cortex-Analyzers/analyzers/' -name requirements.txt -exec pip install -r {} \;

**Comment by nadouani** [comment]
As stated on the latest documentation at https://github.com/CERT-BDF/CortexDocs/blob/master/installation/analyzers.md you can use the following command

```
cd analyzers
sudo pip install $(sort -u */requirements.txt)
```
