### ISSUE TITLE
Add Analyzer for Yeti Platform

### ISSUE THREAD

**Issue by nadouani** [CERT-BDF/Cortex-Analyzers#68]
### Request Type
Analyzer

### Description
This is a request for adding a Yeti analyzer to search for observables of types: "domain", "fqdn", "ip", "url", "hash"

**Comment by nadouani** [comment]
![yeti-long-report](https://user-images.githubusercontent.com/21827/28276178-676b504a-6b16-11e7-8770-ca38e9a47283.png)

**Comment by darksheer** [comment]
I noticed this was added, but the default config in /cortex/application.conf doesn't have the configuration requirements for the analyzer (URL Information)

**Comment by nadouani** [comment]
Hello @darksheer, for analyzers documentation, please refer to https://github.com/CERT-BDF/CortexDocs/blob/master/analyzer_requirements.md
