### ISSUE TITLE
MISPClient.__init__, ssl parameter default to True but later used as filename

### ISSUE THREAD

**Issue by trolldbois** [CERT-BDF/Cortex-Analyzers#87]
MISPClient.__init__, ssl parameter default to True but later used as filename

### Request Type
Bug

### Work Environment
Ubuntu 16
Cortex analyzer name: MISP
Cortex version: 1.1.3

### Description
https://github.com/CERT-BDF/Cortex-Analyzers/blob/4e6cd23e0b41bc5ef5b2b91fa4921cedb0a35773/analyzers/MISP/mispclient.py#L37

Current error using the MISP module:

> TypeError: coercing to Unicode: need string or buffer, bool found

### Steps to Reproduce
1. try to run a MISP analyzer without config.certpath in config path

### Possible Solutions
Fix code to handle bool value in ssl parameter

**Comment by nadouani** [comment]
Hi @3c7, any idea about this one?

Otherwise I can take a look on it.

Thanks

**Comment by 3c7** [comment]
Hi @nadouani, I'll fix it.
