### ISSUE TITLE
MISP_2_0 analyzer does not seems compatible with python 2.7

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/Cortex-Analyzers#90]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| Cortex Analyzer Name      | MISP_2_0
| Cortex Analyzer Version   | 1.6.0
| Cortex Version            | 1.1.3

### Description
When trying to execute a job with the MISP_2_0 analyzer, the job fails due to the following error:
```json
{
  "errorMessage": "Error: Invalid output\n/usr/local/lib/python2.7/dist-packages/pymisp/api.py:21: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4\n  warnings.warn(\"You're using python 2, it is strongly recommended to use python >=3.4\")\n/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:45: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4\n  warnings.warn(\"You're using python 2, it is strongly recommended to use python >=3.4\")\n/usr/local/lib/python2.7/dist-packages/pymisp/api.py:49: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4\n  warnings.warn(\"You're using python 2, it is strongly recommended to use python >=3.4\")\nTraceback (most recent call last):\n  File \"./misp.py\", line 62, in <module>\n    MISPAnalyzer().run()\n  File \"./misp.py\", line 14, in __init__\n    name=self.getParam('config.name', None))\n  File \"/opt/Cortex-Analyzers/analyzers/MISP/mispclient.py\", line 37, in __init__\n    if os.path.isfile(ssl):\n  File \"/usr/lib/python2.7/genericpath.py\", line 37, in isfile\n    st = os.stat(path)\nTypeError: coercing to Unicode: need string or buffer, bool found\n",
  "success": false
}
```

### Steps to Reproduce
1. Run a IP analysis through MISP
2. The job fails with the above error

### Complementary information
I tried to install Cortex with a full python3 stack but some analyzers do not seem compatible with it (pip3 failed to install a few dependencies) and I tried to combine python3 with the MISP analyzer but I am not fluent enough with the environment to force using python3 when calling the MISP analyzer

**Comment by jeromeleonard** [comment]
Hi, 

We have released a bug fix recently that fixed an issue related to that error. Could you please git pull the last version of analyzers and test if it still fails ? 

Regards,

**Comment by srilumpa** [comment]
Hi,

I have just checked and I have the same behaviour with the 1.6.2 version and with the current develop branch.

Best regards,

**Comment by jeromeleonard** [comment]
Hi srilumpa, 

a new version 1.6.3 including the fix from @3c7 has been released. Could you please check if you still have the issue ? 

Regards,

**Comment by srilumpa** [comment]
Hi @jeromeleonard,

I think there is is still an issue, but not linked to the python3 compatibility. I will check this more thoroughly and open an other issue about it.

Otherwise everything seems to work smoothly. Thank you !

Best regards,
