### ISSUE TITLE
VirusTotal URL Scan Bug

### ISSUE THREAD

**Issue by BrevilleBro** [CERT-BDF/Cortex-Analyzers#93]
# VirusTotal URL Scan Bug

### Request Type
Bug 

### Work Environment
N/A

| Question              | Answer
|---------------------------|--------------------
| Cortex Analyzer Name      | VirusTotal
| Cortex Analyzer Version   | 3.0

### Description
When running a VT scan on a URL, if a report already exists, the analyzer will return the old report (not the most recent from the running scan)

### Steps to Reproduce
1. Analyze a URL with a VT report that already exists
1. Notice that the report that comes back (date field) will be incorrect
1. Run the scan again on the same URL and get the previously run scan report

**Comment by saadkadhi** [comment]
Thanks @BrevilleBro. @jeromeleonard will look at it shortly.

**Comment by saadkadhi** [comment]
@jeromeleonard any update on this front? Thanks.
